server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    properties:
      database-platform: com.uns.ac.rs.schedulerservice.configuration.ImprovedMySQLDialect
      hibernate:
        dialect: com.uns.ac.rs.schedulerservice.configuration.ImprovedMySQLDialect
          #storage_engine: innodb
        connection:
          charSet: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
    hibernate:
      naming_stratgey: org.hibernate.cfg.EJB3NamingStrategy
      #ddl-auto: create
      #ddl-auto: update
      ddl-auto: create-drop
    show_sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/scheduler?allowPublicKeyRetrieval=true&useSSL=false
#    initialization-mode: never
    initialization-mode: always
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: simetraehcapa
  cloud:
    config:
      enabled: false

springfox:
  documentation:
    swagger-ui:
      baseUrl: scheduler-service

stripe:
  webhook:
    secret: whsec_479271a8be1ce8a8841a3c15dbc248eaa44d26d1595d76dd7c3d8f6aca920c23
  apiKey: sk_test_51KrplgL8U3BNM2iQy3cCNphQG7vMdewdLMd71f6AljjRRdu7GGJLI8pabmSrBIObbcLMSLIdBqgpP8JFdLr4fmim00qF1P1QZ2

feign-services:
  user-service:
    name: user-service
    url: http://localhost:8081/api/user-service
    path: /user

feign:
  client:
    config:
      default:
        connectTimeout: 200000
        readTimeout: 200000
        loggerLevel: full


minio:
  client:
    username: minioadmin
    password: minioadmin
  bucket:
    endpoint: http://127.0.0.1:9000
    name: scheduler-bucket

swagger:
    title: ^project.name^
    description: ^project.description^
    version: ^project.version^
    termsOfServiceUrl: \#
    contactName: Miljan Puletic
    contactUrl: \#
    contactEmail: miljan.puletic@email.com
    license: License of API
    licenseUrl: \#